### ISSUE TITLE
[Feature request] Default transparency setting

### ISSUE THREAD

**Issue by Kristinita** [ivellioscolin/sublime-plugin-glassit#3]
### 1. Summary

It would be nice, if you add `default_transparency` setting for disable transparency by default or set custom transparency.

### 2. Expected behavior

Custom or disable transparency, when I open Sublime Text.

### 3. Actual behavior

Only `Sublime window transparency is set to 229`, when I open Sublime Text.

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install `SetTransparency.exe` into main Sublime Text path → I install GlassIt via Package Control → I restart Sublime Text → I see in console

`Sublime window transparency is set to 229`

I don't want 229 transparency by default. I want disable transparency by default or set custom transparency. I not find in [**glassit.sublime-settings**](https://github.com/ivellioscolin/sublime-plugin-glassit/blob/master/glassit.sublime-settings) file `default_transparency` setting.

Yes, I can disable transparency via `Tools` → `Packages` → `Glass It` → unchecked `☐ Transparency Enabled` → but if I restart Sublime Text, I have transparency again.

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by ivellioscolin** [comment]
Thanks for your suggestion. I'll make the change very soon.

**Comment by ivellioscolin** [comment]
Hi Kristinita,

Sorry for the late reply. I'm busy with urgent tasks so don't have chance to check.
For the symptom you described, there is a way to make that happen.

As you know ST provides the "user settings" configuration to override "default settings". In the settings, I provide a field "alpha_percentage" to adjust the transparency level. The global default value is 90%, since the Windows API I used to adjust transparency support alpha range [0, 255], that's why you see console outputs "Sublime window transparency is set to 229".

Check if below steps are what you want:

- Preferences->Package Settings->Glass It->Settings - Default, the default value is 90.
- Preferences->Package Settings->Glass It->Settings - User, default should be empty. Add below lines and save.
{
    "alpha_percentage": 100
}
100% indicates not using transparency.
- Restart ST.

**Comment by ivellioscolin** [comment]
I add a feature to change last-changes made by user to settings, so that every new ST open will restore last user settings instead of default settings. Since I've moved to VSC so won't update this plugin until serious issues.
