### ISSUE TITLE
Include SetTransparency.exe

### ISSUE THREAD

**Issue by kapitanluffy** [ivellioscolin/sublime-plugin-glassit#4]
Take a look at this package,
https://github.com/vhanla/SublimeTextTrans

The executable to make the window invisible is already included.
The only deal breaker for me is I can't increment/decrement the opacity unlike `glassit`.

**Comment by ivellioscolin** [comment]
Pass different alpha as one of the SetTransparency.exe parameters can change the opacity. So you are expecting me to add some more functions or what? Sorry I'm not quite clear what's the issue.

**Comment by ivellioscolin** [comment]
The reason I don't package the binary is for security concern. The ST3 plugin is in plain text so that easy to check the security. However the binary could be infected by 3rd party virus on hosted website. Thus I provide the source so that user could compile it themselves. If they trust github they can also manually download from the repo.

**Comment by kapitanluffy** [comment]
Ok. Anyway, I created a batch script for users that may want an easy way to place the executable file in the ST3 directory (after every update) without downloading it from the repo.

https://gist.github.com/kapitanluffy/709b26898341766ed9240ded464f1004

**Comment by ivellioscolin** [comment]
It's great that user will have an alternative. And for those user who don't want manual operations your script do help them a lot. Thanks.
